using System.Security.Cryptography;using Microsoft.AspNetCore.Authentication.Cookies;using Microsoft.EntityFrameworkCore;using Indamin.Payment.Data;using Indamin.Payment.Services;
var b=WebApplication.CreateBuilder(args);
var connectionString=b.Configuration.GetConnectionString("Default");
if(string.IsNullOrWhiteSpace(connectionString))
    connectionString=Environment.GetEnvironmentVariable("SQLSERVER_CONNECTION_STRING");
if(string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("Connection string is not configured. Set ConnectionStrings:Default (or ConnectionStrings__Default in IIS/environment) to a SQL Server connection string. For SQL authentication use User ID and Password; do not use Trusted_Connection/Integrated Security unless Windows authentication is intentionally configured for the application identity.");
b.Services.AddControllersWithViews();b.Services.AddDataProtection();b.Services.AddDbContext<AppDbContext>(o=>o.UseSqlServer(connectionString));b.Services.AddScoped<CompanySettingsService>();b.Services.AddScoped<ExcelService>();b.Services.AddScoped<PaymentCalculationService>();b.Services.AddScoped<PaymentOrderPdfService>();b.Services.AddScoped<SupplierPriorityService>();b.Services.AddScoped<FinancialReportingService>();b.Services.AddScoped<ReportCredentialProtector>();b.Services.AddScoped<InputQueryService>();b.Services.AddDistributedMemoryCache();b.Services.AddSession(o=>{o.Cookie.HttpOnly=true;o.Cookie.IsEssential=true;o.IdleTimeout=TimeSpan.FromHours(4);});b.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(o=>{o.LoginPath="/Account/Login";o.AccessDeniedPath="/Account/Denied";o.ExpireTimeSpan=TimeSpan.FromHours(8);o.SlidingExpiration=true;});b.Services.AddAuthorization(o=>{o.AddPolicy("AdminOnly",p=>p.RequireClaim("IsAdmin","1"));foreach(var d in SecurityPermissions.Definitions)o.AddPolicy("Permission:"+d.Code,p=>p.RequireClaim(SecurityPermissions.Claim,d.Code));});
var app=b.Build();using(var sc=app.Services.CreateScope()){var db=sc.ServiceProvider.GetRequiredService<AppDbContext>();await DatabaseInitializer.InitializeAsync(db);await DatabaseInitializer.EnsureSupplierInitialClaimAsync(db);await DatabaseInitializer.EnsurePaymentSnapshotSchemaAsync(db);await DatabaseInitializer.EnsurePaymentLifecycleSchemaAsync(db);await DatabaseInitializer.EnsureAdvancedPaymentSchemaAsync(db);await DatabaseInitializer.EnsureSecuritySchemaAsync(db);await DatabaseInitializer.EnsureCompanySettingsAsync(db);await DatabaseInitializer.EnsureQueryAndPriceListSchemaAsync(db);await DatabaseInitializer.SeedAsync(db);await DatabaseInitializer.SeedSecurityAsync(db);await DatabaseInitializer.SeedSystemParametersAsync(db);var pwd=app.Configuration["InitialAdminPassword"];if(string.IsNullOrWhiteSpace(pwd))throw new InvalidOperationException("InitialAdminPassword باید تنظیم شود.");if(!await db.Users.AnyAsync(x=>x.IsAdmin)){db.Users.Add(new AppUser{UserName="admin",DisplayName="مدیر سامانه پرداخت",IsAdmin=true,IsActive=true,PasswordHash=PasswordHasher.Hash(pwd)});await db.SaveChangesAsync();}await DatabaseInitializer.EnsureAdministratorRoleAssignmentAsync(db);}
if(!app.Environment.IsDevelopment())app.UseExceptionHandler("/Home/Error");app.UseStaticFiles();app.UseRouting();app.UseSession();app.UseAuthentication();app.UseAuthorization();app.MapControllerRoute("default","{controller=Home}/{action=Index}/{id?}");app.Run();
public static class PasswordHasher{public static string Hash(string v){var s=RandomNumberGenerator.GetBytes(16);var k=Rfc2898DeriveBytes.Pbkdf2(v,s,100000,System.Security.Cryptography.HashAlgorithmName.SHA256,32);return $"100000.{Convert.ToBase64String(s)}.{Convert.ToBase64String(k)}";}public static bool Verify(string v,string st){try{var p=st.Split('.');if(p.Length!=3)return false;var s=Convert.FromBase64String(p[1]);var e=Convert.FromBase64String(p[2]);var k=Rfc2898DeriveBytes.Pbkdf2(v,s,int.Parse(p[0]),System.Security.Cryptography.HashAlgorithmName.SHA256,e.Length);return CryptographicOperations.FixedTimeEquals(k,e);}catch{return false;}}}
