using System.Data;
using System.Text.Json;using Indamin.Payment.Data;using Indamin.Payment.Services;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace Indamin.Payment.Controllers;
[Authorize(Policy="AdminOnly")]public class PaymentWizardController(AppDbContext db,ExcelService excel,PaymentCalculationService calc):Controller{
 const string SessionKey="PaymentWizardState";
 int UserId=>int.TryParse(User.FindFirst("UserId")?.Value,out var id)?id:0;
 public IActionResult Index()=>RedirectToAction(nameof(Step1));
 [HttpGet]public IActionResult Step1(){var s=Load()??new PaymentWizardState{CalculationDateJalali=PersianDateService.ToJalali(DateTime.Today),PeriodFromJalali=PersianDateService.ToJalali(DateTime.Today.AddDays(-30)),PeriodToJalali=PersianDateService.ToJalali(DateTime.Today),Title="محاسبه تخصیص تامین‌کنندگان"};return View(s);}
 [HttpPost][ValidateAntiForgeryToken]public IActionResult Step1(PaymentWizardState s){try{var cd=PersianDateService.Parse(s.CalculationDateJalali);var from=PersianDateService.Parse(s.PeriodFromJalali);var to=PersianDateService.Parse(s.PeriodToJalali);if(to<from)throw new InvalidOperationException("تاریخ پایان دوره نمی‌تواند قبل از تاریخ شروع باشد.");if(s.TotalAllocationBudget<0)throw new InvalidOperationException("مبلغ کل قابل تخصیص نمی‌تواند منفی باشد.");s.CalculationDateJalali=PersianDateService.ToJalali(cd);s.PeriodFromJalali=PersianDateService.ToJalali(from);s.PeriodToJalali=PersianDateService.ToJalali(to);s.Title=string.IsNullOrWhiteSpace(s.Title)?"محاسبه تخصیص تامین‌کنندگان":s.Title.Trim();s.Step=2;Save(s);return RedirectToAction(nameof(Step2));}catch(Exception ex){TempData["Error"]=ex.Message;return View(s);}}
 [HttpGet]public IActionResult Step2(){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));return View(s);}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> Import(IFormFile file){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return View("Step2",s);}try{var rows=excel.ReadPaymentInvoices(file.OpenReadStream(),PersianDateService.Parse,out var errors);var from=PersianDateService.Parse(s.PeriodFromJalali);var to=PersianDateService.Parse(s.PeriodToJalali);var outside=rows.Where(x=>x.ReceiptDate.Date<from.Date||x.ReceiptDate.Date>to.Date).ToList();if(outside.Count>0)errors.Add($"{outside.Count} رکورد خارج از بازه زمانی تعیین‌شده است.");if(errors.Count>0){TempData["Error"]=string.Join(" | ",errors.Take(12));return View("Step2",s);}
 s.SourceFileName=Path.GetFileName(file.FileName);s.MissingParts=[];s.MissingSuppliers=[];
 var partNames=await db.Parts.Where(x=>x.IsActive).Select(x=>x.Title).AsNoTracking().ToListAsync();var supplierNames=await db.Suppliers.Where(x=>x.IsActive).Select(x=>x.Title).AsNoTracking().ToListAsync();
 var knownParts=partNames.Select(Normalize).ToHashSet();var knownSuppliers=supplierNames.Select(Normalize).ToHashSet();
 s.MissingParts=rows.Select(x=>x.PartTitle.Trim()).Where(x=>x!=""&&!knownParts.Contains(Normalize(x))).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x).ToList();
 s.MissingSuppliers=rows.Select(x=>x.SupplierTitle.Trim()).Where(x=>x!=""&&!knownSuppliers.Contains(Normalize(x))).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x).ToList();
 if(s.MissingParts.Count>0||s.MissingSuppliers.Count>0){s.Rows=[];s.Parameters=[];s.ImportedDebt=rows.Sum(x=>x.DebtAmount);s.RemainingDebt=rows.Sum(x=>x.DebtAmount);Save(s);return View("Step2",s);}
 await calc.CalculateAsync(s,rows);s.MissingParts=[];s.MissingSuppliers=[];Save(s);return RedirectToAction(nameof(Step2));}catch(Exception ex){TempData["Error"]=ex.Message;return View("Step2",s);}}
 [HttpPost][ValidateAntiForgeryToken]public IActionResult UpdateScores(List<ScoreEditItem> items){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));foreach(var i in items.Where(x=>x.RowIndex>=0&&x.RowIndex<s.Rows.Count)){var r=s.Rows[i.RowIndex];var cell=r.Scores.FirstOrDefault(x=>x.ParameterId==i.ParameterId);if(cell==null||cell.Source!="ارزیابی قطعه-تامین‌کننده")continue;if(i.Score<1||i.Score>5){TempData["Error"]="امتیاز پارامترهای دستی باید بین 1 تا 5 باشد.";return View("Step2",s);}cell.Score=i.Score;cell.Contribution=Math.Round(i.Score*cell.Weight/100m,6);}foreach(var r in s.Rows){r.WeightedScore=r.Scores.Sum(x=>x.Contribution);}PaymentCalculationService.AllocateBudget(s.TotalAllocationBudget,s.Rows);Save(s);TempData["Result"]="امتیازهای دستی و مبلغ تخصیص‌یافته مجدداً محاسبه شد.";return RedirectToAction(nameof(Step2));}
 [HttpPost][ValidateAntiForgeryToken]public IActionResult GoStep3(){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));if(s.Rows.Count==0){TempData["Error"]="هیچ بدهی باقی‌مانده‌ای برای تخصیص وجود ندارد.";return RedirectToAction(nameof(Step2));}if(s.Rows.Any(r=>r.Scores.Any(x=>x.Source=="ارزیابی قطعه-تامین‌کننده"&&(x.Score<1||x.Score>5)))){TempData["Error"]="تمام پارامترهای دستی باید امتیاز معتبر داشته باشند.";return RedirectToAction(nameof(Step2));}s.Step=3;Save(s);return RedirectToAction(nameof(Step3));}
 [HttpGet]public IActionResult Step3(){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));if(s.Rows.Count==0)return RedirectToAction(nameof(Step2));return View(s);}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> Approve(){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);try{
  var previous=await db.PaymentRunInvoices.Where(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved).GroupBy(x=>x.PaymentKeyHash).Select(g=>new{Key=g.Key,Amount=g.Sum(x=>x.AllocatedAmount)}).ToDictionaryAsync(x=>x.Key,x=>x.Amount);
  foreach(var r in s.Rows){var current=previous.GetValueOrDefault(PaymentCalculationService.KeyHash(r.ReceiptNo,r.Warehouse,r.PartTitle,r.SupplierTitle));if(current!=r.PreviousAllocated)throw new InvalidOperationException($"تخصیص قبلی رسید «{r.ReceiptNo}» تغییر کرده است. لطفاً محاسبه را از ابتدا انجام دهید.");if(r.AllocatedAmount<0||r.AllocatedAmount>r.RemainingDebt)throw new InvalidOperationException($"مبلغ تخصیص‌یافته رسید «{r.ReceiptNo}» نامعتبر است.");}
  var run=new PaymentRun{Title=s.Title,CalculationDateJalali=s.CalculationDateJalali,CalculationDate=s.CalcDate(),PeriodFromJalali=s.PeriodFromJalali,PeriodToJalali=s.PeriodToJalali,PeriodFrom=PersianDateService.Parse(s.PeriodFromJalali),PeriodTo=PersianDateService.Parse(s.PeriodToJalali),TotalAllocationBudget=s.TotalAllocationBudget,AmountUnit=s.AmountUnit,ImportedDebt=s.ImportedDebt,RemainingDebt=s.RemainingDebt,ImportedRowCount=s.Rows.Count,SourceFileName=s.SourceFileName,Notes=s.Notes,Status=PaymentRunStatus.Approved,CreatedBy=UserId,ApprovedBy=UserId,ApprovedAt=DateTime.UtcNow};
  db.PaymentRuns.Add(run);await db.SaveChangesAsync();
  var totalAssigned=s.Rows.Sum(x=>x.AllocatedAmount);foreach(var g in s.Rows.GroupBy(x=>new{x.SupplierId,x.SupplierTitle})){db.PaymentRunSupplierSummaries.Add(new PaymentRunSupplierSummary{PaymentRunId=run.Id,SupplierId=g.Key.SupplierId!.Value,SupplierTitle=g.Key.SupplierTitle,InvoiceCount=g.Count(),RemainingDebt=g.Sum(x=>x.RemainingDebt),AllocatedAmount=g.Sum(x=>x.AllocatedAmount),AllocationPercent=totalAssigned>0?Math.Round(g.Sum(x=>x.AllocatedAmount)/totalAssigned,8):0});}await db.SaveChangesAsync();
  foreach(var r in s.Rows){var inv=new PaymentRunInvoice{PaymentRunId=run.Id,PaymentKeyHash=PaymentCalculationService.KeyHash(r.ReceiptNo,r.Warehouse,r.PartTitle,r.SupplierTitle),ReceiptNo=r.ReceiptNo,Warehouse=r.Warehouse,PartTitle=r.PartTitle,SupplierTitle=r.SupplierTitle,PartId=r.PartId,SupplierId=r.SupplierId,OriginalDebt=r.OriginalDebt,ReceiptDate=r.ReceiptDate,ReceiptDateJalali=r.ReceiptDateJalali,ContractSettlementDays=r.ContractSettlementDays,DebtAgeDays=r.DebtAgeDays,PreviousAllocated=r.PreviousAllocated,RemainingDebt=r.RemainingDebt,WeightedScore=r.WeightedScore,AllocationRatio=r.AllocationRatio,AllocatedAmount=r.AllocatedAmount,SourceRowNumber=r.SourceRowNumber};db.PaymentRunInvoices.Add(inv);await db.SaveChangesAsync();foreach(var sc in r.Scores)db.PaymentInvoiceScores.Add(new PaymentInvoiceScore{PaymentRunInvoiceId=inv.Id,PaymentParameterId=sc.ParameterId,Score=sc.Score,Weight=sc.Weight,WeightedContribution=sc.Contribution,ScoringSource=sc.Source,ParameterTitleSnapshot=sc.ParameterTitle});await db.SaveChangesAsync();}
  db.AuditLogs.Add(new AuditLog{Action="APPROVE",Entity="PaymentRun",EntityId=run.Id.ToString(),Details=$"مبلغ تخصیص: {s.Rows.Sum(x=>x.AllocatedAmount):N0}",UserId=UserId});await db.SaveChangesAsync();await tx.CommitAsync();HttpContext.Session.Remove(SessionKey);TempData["Result"]=$"محاسبه پرداخت با شماره {run.Id} با موفقیت تایید و ثبت شد.";return RedirectToAction(nameof(History));
 }catch(Exception ex){await tx.RollbackAsync();TempData["Error"]=ex.Message;return RedirectToAction(nameof(Step3));}}
 [HttpPost][ValidateAntiForgeryToken]public IActionResult Cancel(){HttpContext.Session.Remove(SessionKey);TempData["Result"]="فرایند محاسبه لغو شد.";return RedirectToAction(nameof(Step1));}
 [HttpGet]public async Task<IActionResult> History(){var rows=await db.PaymentRuns.Include(x=>x.Invoices).OrderByDescending(x=>x.Id).ToListAsync();return View(rows);}
 [HttpGet]public async Task<IActionResult> Details(int id){var x=await db.PaymentRuns.Include(r=>r.SupplierSummaries).Include(r=>r.Invoices).ThenInclude(i=>i.Scores).SingleOrDefaultAsync(r=>r.Id==id);if(x==null)return NotFound();return View(x);}
 [HttpGet]public IActionResult ExportPreview(){var s=Load();if(s==null)return RedirectToAction(nameof(Step1));return File(excel.PaymentRows(s.Rows,s.Parameters),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","payment-calculation.xlsx");}
 [HttpGet]public async Task<IActionResult> ExportRun(int id){var run=await db.PaymentRuns.Include(x=>x.Invoices).ThenInclude(x=>x.Scores).SingleOrDefaultAsync(x=>x.Id==id);if(run==null)return NotFound();var rows=run.Invoices.Select(x=>new PaymentCalculationRow{ReceiptNo=x.ReceiptNo,Warehouse=x.Warehouse,PartTitle=x.PartTitle,SupplierTitle=x.SupplierTitle,OriginalDebt=x.OriginalDebt,PreviousAllocated=x.PreviousAllocated,RemainingDebt=x.RemainingDebt,ContractSettlementDays=x.ContractSettlementDays,DebtAgeDays=x.DebtAgeDays,WeightedScore=x.WeightedScore,AllocationRatio=x.AllocationRatio,AllocatedAmount=x.AllocatedAmount,ReceiptDate=x.ReceiptDate,ReceiptDateJalali=x.ReceiptDateJalali,Scores=x.Scores.Select(sc=>new PaymentScoreResult{ParameterId=sc.PaymentParameterId,ParameterTitle=sc.ParameterTitleSnapshot,Weight=sc.Weight,Score=sc.Score,Contribution=sc.WeightedContribution,Source=sc.ScoringSource}).ToList()}).ToList();var ids=run.Invoices.SelectMany(i=>i.Scores).Select(s=>s.PaymentParameterId).Distinct().ToList();var ps=await db.PaymentParameters.Where(x=>x.IsActive||ids.Contains(x.Id)).OrderBy(x=>x.SortOrder).AsNoTracking().ToListAsync();return File(excel.PaymentRows(rows,ps.Select(x=>new PaymentParameterSnapshot(x.Id,x.Code,x.Title,x.Type,x.Weight,x.MaxScore,x.ScoringGuide,x.ScoringMethod))),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",$"payment-run-{id}.xlsx");}
 [HttpGet]public async Task<IActionResult> ExportSummary(int id){var rows=await db.PaymentRunSupplierSummaries.Where(x=>x.PaymentRunId==id).OrderByDescending(x=>x.AllocatedAmount).Select(x=>new{x.SupplierTitle,x.AllocatedAmount,x.InvoiceCount}).ToListAsync();return File(excel.SupplierSummary(rows.Select(x=>(x.SupplierTitle,x.AllocatedAmount,x.InvoiceCount))),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",$"supplier-summary-{id}.xlsx");}
 PaymentWizardState? Load(){var json=HttpContext.Session.GetString(SessionKey);return string.IsNullOrWhiteSpace(json)?null:JsonSerializer.Deserialize<PaymentWizardState>(json);}
 void Save(PaymentWizardState s)=>HttpContext.Session.SetString(SessionKey,JsonSerializer.Serialize(s));
 static string Normalize(string v)=>(v??"").Trim().Replace("ي","ی").Replace("ك","ک").ToLowerInvariant();
 public class ScoreEditItem{public int RowIndex{get;set;}public int ParameterId{get;set;}public decimal Score{get;set;}}
}
