using Indamin.Payment.Data;using Indamin.Payment.Services;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace Indamin.Payment.Controllers;
[Authorize(Policy="AdminOnly")]public class SetupController(AppDbContext db,ExcelService excel):Controller{
 static string N(string s)=>(s??"").Trim().Replace("ي","ی").Replace("ك","ک").ToLowerInvariant();
 int UserId=>int.TryParse(User.FindFirst("UserId")?.Value,out var id)?id:0;
 async Task Log(string action,string entity,string id,string details){db.AuditLogs.Add(new AuditLog{Action=action,Entity=entity,EntityId=id,Details=details,UserId=UserId});await db.SaveChangesAsync();}
 public async Task<IActionResult> Parameters()=>View(new ParametersVm(await db.PaymentParameters.OrderBy(x=>x.SortOrder).ThenBy(x=>x.Title).ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddParameter(string code,string title,PaymentParameterType type,decimal weight,string scoringGuide,ParameterScoringMethod? method=null,int sortOrder=1){
  var scoringMethod=method ?? ParameterScoringMethod.Manual;code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||weight<0||weight>100)TempData["Error"]="اطلاعات پارامتر نامعتبر است.";else if(await db.PaymentParameters.AnyAsync(x=>x.Code==code))TempData["Error"]="کد پارامتر تکراری است.";else{db.PaymentParameters.Add(new PaymentParameter{Code=code,Title=title,Type=type,Weight=weight,MaxScore=5,ScoringGuide=scoringGuide?.Trim()??"",ScoringMethod=scoringMethod,SortOrder=Math.Max(1,sortOrder)});await db.SaveChangesAsync();await Log("CREATE","PaymentParameter",code,title);TempData["Result"]="پارامتر ایجاد شد.";}return RedirectToAction(nameof(Parameters));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditParameter(int id,string code,string title,PaymentParameterType type,decimal weight,string scoringGuide,ParameterScoringMethod method,int sortOrder,bool isActive=true){
  var p=await db.PaymentParameters.FindAsync(id);if(p==null)return NotFound();code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||weight<0||weight>100)TempData["Error"]="اطلاعات پارامتر نامعتبر است.";else if(await db.PaymentParameters.AnyAsync(x=>x.Id!=id&&x.Code==code))TempData["Error"]="کد پارامتر تکراری است.";else{p.Code=code;p.Title=title;p.Type=type;p.Weight=weight;p.ScoringGuide=scoringGuide?.Trim()??"";p.ScoringMethod=method;p.SortOrder=Math.Max(1,sortOrder);p.IsActive=isActive;await db.SaveChangesAsync();await Log("UPDATE","PaymentParameter",id.ToString(),title);TempData["Result"]="پارامتر به‌روزرسانی شد.";}return RedirectToAction(nameof(Parameters));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ToggleParameter(int id){var p=await db.PaymentParameters.FindAsync(id);if(p==null)return NotFound();p.IsActive=!p.IsActive;await db.SaveChangesAsync();await Log("TOGGLE","PaymentParameter",id.ToString(),p.IsActive?"فعال":"غیرفعال");TempData["Result"]="وضعیت پارامتر تغییر کرد.";return RedirectToAction(nameof(Parameters));}

 public async Task<IActionResult> Lookups(string group="PART_TYPE",string tab="lookup"){var all=await db.LookupValues.OrderBy(x=>x.GroupCode).ThenBy(x=>x.SortOrder).ThenBy(x=>x.Title).ToListAsync();var groups=all.Select(x=>x.GroupCode.Trim().ToUpperInvariant()).Distinct().OrderBy(x=>x).ToList();if(groups.Count==0)group="PART_TYPE";else{group=group.Trim().ToUpperInvariant();if(!groups.Contains(group))group=groups[0];}var rows=groups.ToDictionary(g=>g,g=>all.Where(x=>x.GroupCode.Trim().ToUpperInvariant()==g).ToList());var company=await db.CompanySettings.SingleOrDefaultAsync(x=>x.Id==1)??new CompanySettings();return View(new LookupVm(rows,groups,group,tab,company));}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> SaveCompanySettings(CompanySettings model,IFormFile? logo,IFormFile? favicon,bool removeLogo=false,bool removeFavicon=false){
  var x=await db.CompanySettings.SingleOrDefaultAsync(x=>x.Id==1);if(x==null){x=new CompanySettings();db.CompanySettings.Add(x);}
  if(!ValidColor(model.PrimaryColor)||!ValidColor(model.SecondaryColor)){TempData["Error"]="کد رنگ باید به شکل #RRGGBB باشد.";return RedirectToAction(nameof(Lookups),new{group="PART_TYPE",tab="company"});}x.CompanyName=model.CompanyName?.Trim()??"";x.ShortName=model.ShortName?.Trim()??"";x.SystemName=model.SystemName?.Trim()??"";x.Slogan=model.Slogan?.Trim()??"";x.Website=model.Website?.Trim()??"";x.Phone=model.Phone?.Trim()??"";x.Email=model.Email?.Trim()??"";x.Address=model.Address?.Trim()??"";x.EconomicCode=model.EconomicCode?.Trim()??"";x.NationalId=model.NationalId?.Trim()??"";x.FooterText=model.FooterText?.Trim()??"";x.PrimaryColor=string.IsNullOrWhiteSpace(model.PrimaryColor)?"#102a43":model.PrimaryColor.Trim();x.SecondaryColor=string.IsNullOrWhiteSpace(model.SecondaryColor)?"#2d7fb3":model.SecondaryColor.Trim();
  if(logo is {Length:>0}){if(logo.Length>2*1024*1024){TempData["Error"]="حجم لوگو نباید بیشتر از ۲ مگابایت باشد.";return RedirectToAction(nameof(Lookups),new{group="PART_TYPE",tab="company"});}x.LogoBytes=await ReadImageBytes(logo);x.LogoContentType=logo.ContentType;}else if(removeLogo){x.LogoBytes=null;x.LogoContentType=null;}
  if(favicon is {Length:>0}){if(favicon.Length>1024*1024){TempData["Error"]="حجم favicon نباید بیشتر از ۱ مگابایت باشد.";return RedirectToAction(nameof(Lookups),new{group="PART_TYPE",tab="company"});}x.FaviconBytes=await ReadImageBytes(favicon);x.FaviconContentType=favicon.ContentType;}else if(removeFavicon){x.FaviconBytes=null;x.FaviconContentType=null;}
  x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Log("UPDATE","CompanySettings","1","تنظیمات شرکت/برنامه به‌روزرسانی شد.");TempData["Result"]="تنظیمات شرکت و برنامه ذخیره شد.";return RedirectToAction(nameof(Lookups),new{group="PART_TYPE"});
 }
 static bool ValidColor(string? value)=>!string.IsNullOrWhiteSpace(value)&&value.Length==7&&value[0]=='#'&&value.Skip(1).All(ch=>(ch>='0'&&ch<='9')||(ch>='a'&&ch<='f')||(ch>='A'&&ch<='F'));
 static async Task<byte[]> ReadImageBytes(IFormFile f){using var ms=new MemoryStream();await f.CopyToAsync(ms);return ms.ToArray();}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddLookup(string groupCode,string code,string title,int sortOrder=1){groupCode=(groupCode??"").Trim().ToUpperInvariant();code=code?.Trim()??"";title=title?.Trim()??"";if(groupCode==""||code==""||title=="")TempData["Error"]="گروه، کد و عنوان الزامی است.";else if(await db.LookupValues.AnyAsync(x=>x.GroupCode==groupCode&&x.Code==code))TempData["Error"]="کد در این گروه تکراری است.";else{db.LookupValues.Add(new LookupValue{GroupCode=groupCode,Code=code,Title=title,SortOrder=Math.Max(1,sortOrder)});await db.SaveChangesAsync();TempData["Result"]="آیتم اطلاعات پایه ایجاد شد.";}return RedirectToAction(nameof(Lookups),new{group=groupCode});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditLookup(int id,string code,string title,int sortOrder,bool isActive=true,string group="PART_TYPE"){var x=await db.LookupValues.FindAsync(id);if(x==null)return NotFound();code=code?.Trim()??"";title=title?.Trim()??"";if(await db.LookupValues.AnyAsync(y=>y.Id!=id&&y.GroupCode==x.GroupCode&&y.Code==code))TempData["Error"]="کد تکراری است.";else{x.Code=code;x.Title=title;x.SortOrder=Math.Max(1,sortOrder);x.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="آیتم به‌روزرسانی شد.";}return RedirectToAction(nameof(Lookups),new{group});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ToggleLookup(int id,string group="PART_TYPE"){var x=await db.LookupValues.FindAsync(id);if(x==null)return NotFound();x.IsActive=!x.IsActive;await db.SaveChangesAsync();return RedirectToAction(nameof(Lookups),new{group});}

 public async Task<IActionResult> Parts(){var rows=await db.Parts.Include(x=>x.Type).OrderBy(x=>x.Code).ToListAsync();var locked=await db.PaymentRunInvoices.Where(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.PartId.HasValue).Select(x=>x.PartId!.Value).Distinct().ToHashSetAsync();return View(new PartsVm(rows,await db.LookupValues.Where(x=>x.GroupCode=="PART_TYPE"&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync(),locked));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddPart(string code,string title,int typeId,bool isActive=true){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||!await db.LookupValues.AnyAsync(x=>x.Id==typeId&&x.GroupCode=="PART_TYPE"&&x.IsActive))TempData["Error"]="اطلاعات کالا نامعتبر است.";else if(await db.Parts.AnyAsync(x=>x.Code==code))TempData["Error"]="کد قطعه تکراری است.";else{db.Parts.Add(new Part{Code=code,Title=title,TypeId=typeId,IsActive=isActive});await db.SaveChangesAsync();TempData["Result"]="قطعه ایجاد شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditPart(int id,string code,string title,int typeId,bool isActive=true){var p=await db.Parts.FindAsync(id);if(p==null)return NotFound();if(await db.Parts.AnyAsync(x=>x.Id!=id&&x.Code==code.Trim()))TempData["Error"]="کد قطعه تکراری است.";else{p.Code=code.Trim();p.Title=title.Trim();p.TypeId=typeId;p.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="قطعه به‌روزرسانی شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeletePart(int id){var p=await db.Parts.FindAsync(id);if(p==null)return NotFound();if(await db.PaymentRunInvoices.AnyAsync(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.PartId==id)){p.IsActive=false;await db.SaveChangesAsync();TempData["Error"]="قطعه در محاسبه تاییدشده استفاده شده و فقط غیرفعال شد.";}else{db.Parts.Remove(p);await db.SaveChangesAsync();TempData["Result"]="قطعه حذف شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ImportParts(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(Parts));}var types=await db.LookupValues.Where(x=>x.GroupCode=="PART_TYPE"&&x.IsActive).ToDictionaryAsync(x=>N(x.Title),x=>x.Id);List<string> errors;List<PartImportRow> rows;try{rows=excel.ReadParts(file.OpenReadStream(),types,out errors);}catch{TempData["Error"]="خواندن فایل Excel ناموفق بود.";return RedirectToAction(nameof(Parts));}foreach(var x in rows){var p=await db.Parts.SingleOrDefaultAsync(z=>z.Code==x.Code);if(p==null)db.Parts.Add(new Part{Code=x.Code,Title=x.Title,TypeId=x.TypeId,IsActive=x.IsActive});else{p.Title=x.Title;p.TypeId=x.TypeId;p.IsActive=x.IsActive;}}await db.SaveChangesAsync();TempData["Result"]=$"{rows.Count} قطعه وارد/به‌روزرسانی شد."+(errors.Count>0?$" {errors.Count} خطا داشت.":"");return RedirectToAction(nameof(Parts));}
 public async Task<IActionResult> ExportParts(){var x=await db.Parts.Include(p=>p.Type).OrderBy(p=>p.Code).ToListAsync();return File(excel.Parts(x),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","parts.xlsx");}

 public async Task<IActionResult> Suppliers(){var rows=await db.Suppliers.Include(x=>x.Activities).ThenInclude(x=>x.Activity).OrderBy(x=>x.Code).ToListAsync();var locked=await db.PaymentRunInvoices.Where(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.SupplierId.HasValue).Select(x=>x.SupplierId!.Value).Distinct().ToHashSetAsync();return View(new SuppliersVm(rows,await db.LookupValues.Where(x=>x.GroupCode=="SUPPLIER_ACTIVITY"&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync(),locked));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddSupplier(string code,string title,decimal initialClaimAmount,int[]? activityIds,bool isActive=true){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||initialClaimAmount<0||(activityIds??[]).Length==0)TempData["Error"]="کد، عنوان و حداقل یک حوزه فعالیت الزامی است.";else if(await db.Suppliers.AnyAsync(x=>x.Code==code))TempData["Error"]="کد تامین‌کننده تکراری است.";else{var s=new Supplier{Code=code,Title=title,InitialClaimAmount=Math.Round(initialClaimAmount,2),IsActive=isActive};db.Suppliers.Add(s);await db.SaveChangesAsync();db.SupplierActivities.AddRange((activityIds??[]).Distinct().Select(a=>new SupplierActivity{SupplierId=s.Id,ActivityId=a}));await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده ایجاد شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditSupplier(int id,string code,string title,decimal initialClaimAmount,int[] activityIds,bool isActive=true){var s=await db.Suppliers.Include(x=>x.Activities).SingleOrDefaultAsync(x=>x.Id==id);if(s==null)return NotFound();if(await db.Suppliers.AnyAsync(x=>x.Id!=id&&x.Code==code.Trim()))TempData["Error"]="کد تامین‌کننده تکراری است.";else if(initialClaimAmount<0)TempData["Error"]="مبلغ مطالبات استقراری نمی‌تواند منفی باشد.";else{db.SupplierActivities.RemoveRange(s.Activities);s.Code=code.Trim();s.Title=title.Trim();s.InitialClaimAmount=Math.Round(initialClaimAmount,2);s.IsActive=isActive;await db.SaveChangesAsync();db.SupplierActivities.AddRange(activityIds.Distinct().Select(a=>new SupplierActivity{SupplierId=id,ActivityId=a}));await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده به‌روزرسانی شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeleteSupplier(int id){var s=await db.Suppliers.FindAsync(id);if(s==null)return NotFound();if(await db.PaymentRunInvoices.AnyAsync(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.SupplierId==id)){s.IsActive=false;await db.SaveChangesAsync();TempData["Error"]="تامین‌کننده در محاسبه تاییدشده استفاده شده و فقط غیرفعال شد.";}else{db.Suppliers.Remove(s);await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده حذف شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ImportSuppliers(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(Suppliers));}var acts=await db.LookupValues.Where(x=>x.GroupCode=="SUPPLIER_ACTIVITY"&&x.IsActive).ToDictionaryAsync(x=>N(x.Title),x=>x.Id);List<string> errors;List<SupplierImportRow> rows;try{rows=excel.ReadSuppliers(file.OpenReadStream(),acts,out errors);}catch{TempData["Error"]="خواندن فایل Excel ناموفق بود.";return RedirectToAction(nameof(Suppliers));}foreach(var x in rows){var s=await db.Suppliers.Include(z=>z.Activities).SingleOrDefaultAsync(z=>z.Code==x.Code);if(s==null){s=new Supplier{Code=x.Code,Title=x.Title,InitialClaimAmount=Math.Round(x.InitialClaimAmount,2),IsActive=x.IsActive};db.Suppliers.Add(s);await db.SaveChangesAsync();}else{s.Title=x.Title;s.InitialClaimAmount=Math.Round(x.InitialClaimAmount,2);s.IsActive=x.IsActive;db.SupplierActivities.RemoveRange(s.Activities);await db.SaveChangesAsync();}db.SupplierActivities.AddRange(x.ActivityIds.Select(a=>new SupplierActivity{SupplierId=s.Id,ActivityId=a}));}await db.SaveChangesAsync();TempData["Result"]=$"{rows.Count} تامین‌کننده وارد/به‌روزرسانی شد."+(errors.Count>0?$" {errors.Count} خطا داشت.":"");return RedirectToAction(nameof(Suppliers));}
 public async Task<IActionResult> ExportSuppliers(){var x=await db.Suppliers.Include(s=>s.Activities).ThenInclude(a=>a.Activity).OrderBy(s=>s.Code).ToListAsync();return File(excel.Suppliers(x),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","suppliers.xlsx");}

 public async Task<IActionResult> Mappings(){var rows=await db.SupplierParts.Include(x=>x.Supplier).Include(x=>x.Part).OrderBy(x=>x.Supplier!.Title).ThenBy(x=>x.Part!.Title).ToListAsync();var locked=await db.PaymentRunInvoices.Where(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.PartId.HasValue&&x.SupplierId.HasValue).Select(x=>new{x.PartId,x.SupplierId}).ToListAsync();var lockedIds=rows.Where(m=>locked.Any(x=>x.PartId==m.PartId&&x.SupplierId==m.SupplierId)).Select(x=>x.Id).ToHashSet();return View(new MappingsVm(rows,await db.Suppliers.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync(),await db.Parts.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync(),lockedIds));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> SaveMapping(int? id,int supplierId,int partId,decimal supplyCapacity,int contractSettlementDays,bool isActive=true){if(supplyCapacity<0||contractSettlementDays<=0)TempData["Error"]="ظرفیت و مهلت قراردادی نامعتبر است.";else if(await db.SupplierParts.AnyAsync(x=>x.Id!=id&&x.SupplierId==supplierId&&x.PartId==partId))TempData["Error"]="این ارتباط قبلاً تعریف شده است.";else{var m=id.HasValue?await db.SupplierParts.FindAsync(id):null;if(m==null){m=new SupplierPart{SupplierId=supplierId,PartId=partId};db.SupplierParts.Add(m);}else if(await db.PaymentRunInvoices.AnyAsync(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.PartId==m.PartId&&x.SupplierId==m.SupplierId)){if(m.SupplierId!=supplierId||m.PartId!=partId){TempData["Error"]="این ارتباط در محاسبه تاییدشده استفاده شده و تامین‌کننده/کالا قابل تغییر نیست؛ فقط وضعیت فعال بودن قابل تغییر است.";}else{m.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="این ارتباط قبلاً در محاسبه تاییدشده استفاده شده؛ فقط وضعیت فعال/غیرفعال تغییر کرد.";}return RedirectToAction(nameof(Mappings));}m.SupplierId=supplierId;m.PartId=partId;m.SupplyCapacity=supplyCapacity;m.ContractSettlementDays=contractSettlementDays;m.IsActive=isActive;await db.SaveChangesAsync();await EnsureDefaultEvaluationsAsync(m.Id);TempData["Result"]="ارتباط قطعه–تامین‌کننده ذخیره شد.";}return RedirectToAction(nameof(Mappings));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeleteMapping(int id){var m=await db.SupplierParts.FindAsync(id);if(m==null)return NotFound();var used=await db.PaymentRunInvoices.AnyAsync(x=>x.PaymentRun!.Status==PaymentRunStatus.Approved&&x.PartId==m.PartId&&x.SupplierId==m.SupplierId);if(used){m.IsActive=false;await db.SaveChangesAsync();TempData["Error"]="این ارتباط در محاسبه تاییدشده استفاده شده و قابل حذف نیست؛ فقط غیرفعال شد.";}else{db.SupplierParts.Remove(m);await db.SaveChangesAsync();TempData["Result"]="ارتباط حذف شد.";}return RedirectToAction(nameof(Mappings));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ImportMappings(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(Mappings));}var suppliers=await db.Suppliers.ToDictionaryAsync(x=>N(x.Code),x=>x.Id);var parts=await db.Parts.ToDictionaryAsync(x=>N(x.Code),x=>x.Id);List<string> errors;List<SupplierPartImportRow> rows;try{rows=excel.ReadSupplierParts(file.OpenReadStream(),suppliers,parts,out errors);}catch{TempData["Error"]="خواندن فایل Excel ارتباط کالا و تامین‌کننده ناموفق بود.";return RedirectToAction(nameof(Mappings));}var seen=new HashSet<string>();var existing=await db.SupplierParts.ToDictionaryAsync(x=>$"{x.SupplierId}:{x.PartId}");var affected=0;foreach(var x in rows){var key=$"{x.SupplierId}:{x.PartId}";if(!seen.Add(key)){errors.Add($"سطر {x.RowNumber}: ارتباط تکراری تامین‌کننده و کالا در فایل.");continue;}if(existing.TryGetValue(key,out var m)){m.SupplyCapacity=x.SupplyCapacity;m.ContractSettlementDays=x.ContractSettlementDays;m.IsActive=x.IsActive;affected++;}else{db.SupplierParts.Add(new SupplierPart{SupplierId=x.SupplierId,PartId=x.PartId,SupplyCapacity=x.SupplyCapacity,ContractSettlementDays=x.ContractSettlementDays,IsActive=x.IsActive});affected++;}}await db.SaveChangesAsync();foreach(var x in rows){var m=await db.SupplierParts.SingleOrDefaultAsync(z=>z.SupplierId==x.SupplierId&&z.PartId==x.PartId);if(m!=null)await EnsureDefaultEvaluationsAsync(m.Id);}TempData["Result"]=$"{affected} ارتباط وارد/به‌روزرسانی شد."+(errors.Count>0?$" {errors.Count} خطا داشت.":"");return RedirectToAction(nameof(Mappings));}
 public async Task<IActionResult> ExportMappings(){var x=await db.SupplierParts.Include(m=>m.Supplier).Include(m=>m.Part).OrderBy(m=>m.Supplier!.Code).ThenBy(m=>m.Part!.Code).ToListAsync();return File(excel.SupplierParts(x),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","supplier-part-mappings.xlsx");}

 public async Task<IActionResult> Evaluations(){var maps=await db.SupplierParts.Include(x=>x.Supplier).Include(x=>x.Part).Where(x=>x.IsActive).OrderBy(x=>x.Supplier!.Title).ThenBy(x=>x.Part!.Title).ToListAsync();foreach(var m in maps)await EnsureDefaultEvaluationsAsync(m.Id);return View(new EvaluationsVm(maps,await db.PaymentParameters.Where(x=>x.IsActive&&x.ScoringMethod==ParameterScoringMethod.Manual).OrderBy(x=>x.SortOrder).ToListAsync(),await db.SupplierPartEvaluations.AsNoTracking().ToListAsync()));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> SaveEvaluations(int supplierPartId,List<EvaluationEditItem> items){var map=await db.SupplierParts.SingleOrDefaultAsync(x=>x.Id==supplierPartId);if(map==null)return NotFound();var activeParameters=await db.PaymentParameters.Where(x=>x.IsActive&&x.ScoringMethod==ParameterScoringMethod.Manual).ToListAsync();foreach(var p in activeParameters){var item=items.FirstOrDefault(x=>x.ParameterId==p.Id);if(item==null||item.Score<1||item.Score>p.MaxScore){TempData["Error"]=$"امتیاز «{p.Title}» باید بین ۱ تا {p.MaxScore:0.##} باشد.";return RedirectToAction(nameof(Evaluations));}var x=await db.SupplierPartEvaluations.SingleOrDefaultAsync(a=>a.SupplierPartId==supplierPartId&&a.PaymentParameterId==p.Id);if(x==null)db.SupplierPartEvaluations.Add(new SupplierPartEvaluation{SupplierPartId=supplierPartId,PaymentParameterId=p.Id,Score=item.Score,IsActive=true});else{x.Score=item.Score;x.IsActive=true;x.UpdatedAt=DateTime.UtcNow;}}await db.SaveChangesAsync();TempData["Result"]="تمام امتیازهای این ارتباط با موفقیت ثبت شد.";return RedirectToAction(nameof(Evaluations));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ToggleEvaluationSet(int supplierPartId){var map=await db.SupplierParts.FindAsync(supplierPartId);if(map==null)return NotFound();var xs=await db.SupplierPartEvaluations.Where(x=>x.SupplierPartId==supplierPartId).ToListAsync();var next=xs.Count==0||xs.Any(x=>!x.IsActive);foreach(var x in xs){x.IsActive=next;x.UpdatedAt=DateTime.UtcNow;}await db.SaveChangesAsync();TempData["Result"]=next?"ارزیابی‌های این ارتباط فعال شد.":"ارزیابی‌های این ارتباط غیرفعال شد.";return RedirectToAction(nameof(Evaluations));}
 public async Task<IActionResult> ExportEvaluations(){var activeMaps=await db.SupplierParts.Where(x=>x.IsActive).Select(x=>x.Id).ToListAsync();foreach(var id in activeMaps)await EnsureDefaultEvaluationsAsync(id);var maps=await db.SupplierParts.Include(x=>x.Supplier).Include(x=>x.Part).OrderBy(x=>x.Supplier!.Title).ThenBy(x=>x.Part!.Title).ToListAsync();var ps=await db.PaymentParameters.Where(x=>x.IsActive&&x.ScoringMethod==ParameterScoringMethod.Manual).OrderBy(x=>x.SortOrder).ToListAsync();var scores=await db.SupplierPartEvaluations.AsNoTracking().ToListAsync();return File(excel.SupplierPartEvaluations(maps,ps,scores),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","supplier-part-evaluations.xlsx");}
 async Task EnsureDefaultEvaluationsAsync(int supplierPartId){var ps=await db.PaymentParameters.Where(x=>x.IsActive&&x.ScoringMethod==ParameterScoringMethod.Manual).Select(x=>x.Id).ToListAsync();var existing=await db.SupplierPartEvaluations.Where(x=>x.SupplierPartId==supplierPartId).Select(x=>x.PaymentParameterId).ToListAsync();var missing=ps.Except(existing).Select(id=>new SupplierPartEvaluation{SupplierPartId=supplierPartId,PaymentParameterId=id,Score=1m,IsActive=true}).ToList();if(missing.Count>0){db.SupplierPartEvaluations.AddRange(missing);await db.SaveChangesAsync();}}
 public record EvaluationEditItem(int ParameterId,decimal Score);

 public record ParametersVm(List<PaymentParameter> Rows);public record LookupVm(Dictionary<string,List<LookupValue>> Rows,List<string> Groups,string Group,string Tab,CompanySettings Company);
 public record PartsVm(List<Part> Rows,List<LookupValue> Types,HashSet<int> LockedIds);public record SuppliersVm(List<Supplier> Rows,List<LookupValue> Activities,HashSet<int> LockedIds);
 public record MappingsVm(List<SupplierPart> Rows,List<Supplier> Suppliers,List<Part> Parts,HashSet<int> LockedIds);public record EvaluationsVm(List<SupplierPart> Mappings,List<PaymentParameter> Parameters,List<SupplierPartEvaluation> Scores);
}