using Indamin.Payment.Data;using Indamin.Payment.Services;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace Indamin.Payment.Controllers;
[Authorize(Policy="AdminOnly")]public class SetupController(AppDbContext db,ExcelService excel):Controller{
 static string N(string s)=>(s??"").Trim().Replace("ي","ی").Replace("ك","ک").ToLowerInvariant();
 int UserId=>int.TryParse(User.FindFirst("UserId")?.Value,out var id)?id:0;
 async Task Log(string action,string entity,string id,string details){db.AuditLogs.Add(new AuditLog{Action=action,Entity=entity,EntityId=id,Details=details,UserId=UserId});await db.SaveChangesAsync();}
 public async Task<IActionResult> Parameters()=>View(new ParametersVm(await db.PaymentParameters.OrderBy(x=>x.SortOrder).ThenBy(x=>x.Title).ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddParameter(string code,string title,PaymentParameterType type,decimal weight,string scoringGuide,ParameterScoringMethod method=int.MinValue,int sortOrder=1){
  if(method==(ParameterScoringMethod)int.MinValue)method=ParameterScoringMethod.Manual;code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||weight<0||weight>100)TempData["Error"]="اطلاعات پارامتر نامعتبر است.";else if(await db.PaymentParameters.AnyAsync(x=>x.Code==code))TempData["Error"]="کد پارامتر تکراری است.";else{db.PaymentParameters.Add(new PaymentParameter{Code=code,Title=title,Type=type,Weight=weight,MaxScore=5,ScoringGuide=scoringGuide?.Trim()??"",ScoringMethod=method,SortOrder=Math.Max(1,sortOrder)});await db.SaveChangesAsync();await Log("CREATE","PaymentParameter",code,title);TempData["Result"]="پارامتر ایجاد شد.";}return RedirectToAction(nameof(Parameters));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditParameter(int id,string code,string title,PaymentParameterType type,decimal weight,string scoringGuide,ParameterScoringMethod method,int sortOrder,bool isActive=true){
  var p=await db.PaymentParameters.FindAsync(id);if(p==null)return NotFound();code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||weight<0||weight>100)TempData["Error"]="اطلاعات پارامتر نامعتبر است.";else if(await db.PaymentParameters.AnyAsync(x=>x.Id!=id&&x.Code==code))TempData["Error"]="کد پارامتر تکراری است.";else{p.Code=code;p.Title=title;p.Type=type;p.Weight=weight;p.ScoringGuide=scoringGuide?.Trim()??"";p.ScoringMethod=method;p.SortOrder=Math.Max(1,sortOrder);p.IsActive=isActive;await db.SaveChangesAsync();await Log("UPDATE","PaymentParameter",id.ToString(),title);TempData["Result"]="پارامتر به‌روزرسانی شد.";}return RedirectToAction(nameof(Parameters));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ToggleParameter(int id){var p=await db.PaymentParameters.FindAsync(id);if(p==null)return NotFound();p.IsActive=!p.IsActive;await db.SaveChangesAsync();await Log("TOGGLE","PaymentParameter",id.ToString(),p.IsActive?"فعال":"غیرفعال");TempData["Result"]="وضعیت پارامتر تغییر کرد.";return RedirectToAction(nameof(Parameters));}

 public async Task<IActionResult> Lookups(string group="PART_TYPE"){var rows=await db.LookupValues.Where(x=>x.GroupCode==group).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Title).ToListAsync();var groups=await db.LookupValues.Select(x=>x.GroupCode).Distinct().OrderBy(x=>x).ToListAsync();return View(new LookupVm(rows,groups,group));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddLookup(string groupCode,string code,string title,int sortOrder=1){groupCode=N(groupCode);code=code?.Trim()??"";title=title?.Trim()??"";if(groupCode==""||code==""||title=="")TempData["Error"]="گروه، کد و عنوان الزامی است.";else if(await db.LookupValues.AnyAsync(x=>x.GroupCode==groupCode&&x.Code==code))TempData["Error"]="کد در این گروه تکراری است.";else{db.LookupValues.Add(new LookupValue{GroupCode=groupCode,Code=code,Title=title,SortOrder=Math.Max(1,sortOrder)});await db.SaveChangesAsync();TempData["Result"]="آیتم اطلاعات پایه ایجاد شد.";}return RedirectToAction(nameof(Lookups),new{group=groupCode});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditLookup(int id,string code,string title,int sortOrder,bool isActive=true,string group="PART_TYPE"){var x=await db.LookupValues.FindAsync(id);if(x==null)return NotFound();code=code?.Trim()??"";title=title?.Trim()??"";if(await db.LookupValues.AnyAsync(y=>y.Id!=id&&y.GroupCode==x.GroupCode&&y.Code==code))TempData["Error"]="کد تکراری است.";else{x.Code=code;x.Title=title;x.SortOrder=Math.Max(1,sortOrder);x.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="آیتم به‌روزرسانی شد.";}return RedirectToAction(nameof(Lookups),new{group});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ToggleLookup(int id,string group="PART_TYPE"){var x=await db.LookupValues.FindAsync(id);if(x==null)return NotFound();x.IsActive=!x.IsActive;await db.SaveChangesAsync();return RedirectToAction(nameof(Lookups),new{group});}

 public async Task<IActionResult> Parts()=>View(new PartsVm(await db.Parts.Include(x=>x.Type).OrderBy(x=>x.Code).ToListAsync(),await db.LookupValues.Where(x=>x.GroupCode=="PART_TYPE"&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddPart(string code,string title,int typeId,bool isActive=true){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||!await db.LookupValues.AnyAsync(x=>x.Id==typeId&&x.GroupCode=="PART_TYPE"&&x.IsActive))TempData["Error"]="اطلاعات کالا نامعتبر است.";else if(await db.Parts.AnyAsync(x=>x.Code==code))TempData["Error"]="کد قطعه تکراری است.";else{db.Parts.Add(new Part{Code=code,Title=title,TypeId=typeId,IsActive=isActive});await db.SaveChangesAsync();TempData["Result"]="قطعه ایجاد شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditPart(int id,string code,string title,int typeId,bool isActive=true){var p=await db.Parts.FindAsync(id);if(p==null)return NotFound();if(await db.Parts.AnyAsync(x=>x.Id!=id&&x.Code==code.Trim()))TempData["Error"]="کد قطعه تکراری است.";else{p.Code=code.Trim();p.Title=title.Trim();p.TypeId=typeId;p.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="قطعه به‌روزرسانی شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeletePart(int id){var p=await db.Parts.FindAsync(id);if(p==null)return NotFound();if(await db.SupplierParts.AnyAsync(x=>x.PartId==id)){p.IsActive=false;await db.SaveChangesAsync();TempData["Error"]="قطعه دارای ارتباط تامین‌کننده است و حذف فیزیکی نشد؛ غیرفعال شد.";}else{db.Parts.Remove(p);await db.SaveChangesAsync();TempData["Result"]="قطعه حذف شد.";}return RedirectToAction(nameof(Parts));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ImportParts(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(Parts));}var types=await db.LookupValues.Where(x=>x.GroupCode=="PART_TYPE"&&x.IsActive).ToDictionaryAsync(x=>N(x.Title),x=>x.Id);List<string> errors;List<PartImportRow> rows;try{rows=excel.ReadParts(file.OpenReadStream(),types,out errors);}catch{TempData["Error"]="خواندن فایل Excel ناموفق بود.";return RedirectToAction(nameof(Parts));}foreach(var x in rows){var p=await db.Parts.SingleOrDefaultAsync(z=>z.Code==x.Code);if(p==null)db.Parts.Add(new Part{Code=x.Code,Title=x.Title,TypeId=x.TypeId,IsActive=x.IsActive});else{p.Title=x.Title;p.TypeId=x.TypeId;p.IsActive=x.IsActive;}}await db.SaveChangesAsync();TempData["Result"]=$"{rows.Count} قطعه وارد/به‌روزرسانی شد."+(errors.Count>0?$" {errors.Count} خطا داشت.":"");return RedirectToAction(nameof(Parts));}
 public async Task<IActionResult> ExportParts(){var x=await db.Parts.Include(p=>p.Type).OrderBy(p=>p.Code).ToListAsync();return File(excel.Parts(x),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","parts.xlsx");}

 public async Task<IActionResult> Suppliers()=>View(new SuppliersVm(await db.Suppliers.Include(x=>x.Activities).ThenInclude(x=>x.Activity).OrderBy(x=>x.Code).ToListAsync(),await db.LookupValues.Where(x=>x.GroupCode=="SUPPLIER_ACTIVITY"&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddSupplier(string code,string title,int[]? activityIds,bool isActive=true){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title==""||(activityIds??[]).Length==0)TempData["Error"]="کد، عنوان و حداقل یک حوزه فعالیت الزامی است.";else if(await db.Suppliers.AnyAsync(x=>x.Code==code))TempData["Error"]="کد تامین‌کننده تکراری است.";else{var s=new Supplier{Code=code,Title=title,IsActive=isActive};db.Suppliers.Add(s);await db.SaveChangesAsync();db.SupplierActivities.AddRange((activityIds??[]).Distinct().Select(a=>new SupplierActivity{SupplierId=s.Id,ActivityId=a}));await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده ایجاد شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditSupplier(int id,string code,string title,int[] activityIds,bool isActive=true){var s=await db.Suppliers.Include(x=>x.Activities).SingleOrDefaultAsync(x=>x.Id==id);if(s==null)return NotFound();if(await db.Suppliers.AnyAsync(x=>x.Id!=id&&x.Code==code.Trim()))TempData["Error"]="کد تامین‌کننده تکراری است.";else{db.SupplierActivities.RemoveRange(s.Activities);s.Code=code.Trim();s.Title=title.Trim();s.IsActive=isActive;await db.SaveChangesAsync();db.SupplierActivities.AddRange(activityIds.Distinct().Select(a=>new SupplierActivity{SupplierId=id,ActivityId=a}));await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده به‌روزرسانی شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeleteSupplier(int id){var s=await db.Suppliers.FindAsync(id);if(s==null)return NotFound();if(await db.SupplierParts.AnyAsync(x=>x.SupplierId==id)){s.IsActive=false;await db.SaveChangesAsync();TempData["Error"]="تامین‌کننده دارای ارتباط است و فقط غیرفعال شد.";}else{db.Suppliers.Remove(s);await db.SaveChangesAsync();TempData["Result"]="تامین‌کننده حذف شد.";}return RedirectToAction(nameof(Suppliers));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ImportSuppliers(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(Suppliers));}var acts=await db.LookupValues.Where(x=>x.GroupCode=="SUPPLIER_ACTIVITY"&&x.IsActive).ToDictionaryAsync(x=>N(x.Title),x=>x.Id);List<string> errors;List<SupplierImportRow> rows;try{rows=excel.ReadSuppliers(file.OpenReadStream(),acts,out errors);}catch{TempData["Error"]="خواندن فایل Excel ناموفق بود.";return RedirectToAction(nameof(Suppliers));}foreach(var x in rows){var s=await db.Suppliers.Include(z=>z.Activities).SingleOrDefaultAsync(z=>z.Code==x.Code);if(s==null){s=new Supplier{Code=x.Code,Title=x.Title,IsActive=x.IsActive};db.Suppliers.Add(s);await db.SaveChangesAsync();}else{s.Title=x.Title;s.IsActive=x.IsActive;db.SupplierActivities.RemoveRange(s.Activities);await db.SaveChangesAsync();}db.SupplierActivities.AddRange(x.ActivityIds.Select(a=>new SupplierActivity{SupplierId=s.Id,ActivityId=a}));}await db.SaveChangesAsync();TempData["Result"]=$"{rows.Count} تامین‌کننده وارد/به‌روزرسانی شد."+(errors.Count>0?$" {errors.Count} خطا داشت.":"");return RedirectToAction(nameof(Suppliers));}
 public async Task<IActionResult> ExportSuppliers(){var x=await db.Suppliers.Include(s=>s.Activities).ThenInclude(a=>a.Activity).OrderBy(s=>s.Code).ToListAsync();return File(excel.Suppliers(x),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","suppliers.xlsx");}

 public async Task<IActionResult> Mappings()=>View(new MappingsVm(await db.SupplierParts.Include(x=>x.Supplier).Include(x=>x.Part).OrderBy(x=>x.Supplier!.Title).ThenBy(x=>x.Part!.Title).ToListAsync(),await db.Suppliers.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync(),await db.Parts.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> SaveMapping(int? id,int supplierId,int partId,decimal supplyCapacity,int contractSettlementDays,bool isActive=true){if(supplyCapacity<0||contractSettlementDays<=0)TempData["Error"]="ظرفیت و مهلت قراردادی نامعتبر است.";else if(await db.SupplierParts.AnyAsync(x=>x.Id!=id&&x.SupplierId==supplierId&&x.PartId==partId))TempData["Error"]="این ارتباط قبلاً تعریف شده است.";else{var m=id.HasValue?await db.SupplierParts.FindAsync(id):null;if(m==null){m=new SupplierPart{SupplierId=supplierId,PartId=partId};db.SupplierParts.Add(m);}m.SupplierId=supplierId;m.PartId=partId;m.SupplyCapacity=supplyCapacity;m.ContractSettlementDays=contractSettlementDays;m.IsActive=isActive;await db.SaveChangesAsync();TempData["Result"]="ارتباط قطعه–تامین‌کننده ذخیره شد.";}return RedirectToAction(nameof(Mappings));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeleteMapping(int id){var m=await db.SupplierParts.FindAsync(id);if(m!=null){db.SupplierParts.Remove(m);await db.SaveChangesAsync();}return RedirectToAction(nameof(Mappings));}

 public async Task<IActionResult> Evaluations()=>View(new EvaluationsVm(
  await db.SupplierParts.Include(x=>x.Supplier).Include(x=>x.Part).Where(x=>x.IsActive).OrderBy(x=>x.Supplier!.Title).ThenBy(x=>x.Part!.Title).ToListAsync(),
  await db.PaymentParameters.Where(x=>x.IsActive&&x.ScoringMethod==ParameterScoringMethod.Manual).OrderBy(x=>x.SortOrder).ToListAsync(),
  await db.SupplierPartEvaluations.AsNoTracking().ToListAsync()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> SaveEvaluation(int supplierPartId,int parameterId,decimal score,string? comment){if(score<1||score>5){TempData["Error"]="امتیاز باید بین 1 تا 5 باشد.";return RedirectToAction(nameof(Evaluations));}var x=await db.SupplierPartEvaluations.SingleOrDefaultAsync(a=>a.SupplierPartId==supplierPartId&&a.PaymentParameterId==parameterId);if(x==null)db.SupplierPartEvaluations.Add(new SupplierPartEvaluation{SupplierPartId=supplierPartId,PaymentParameterId=parameterId,Score=score,Comment=comment?.Trim()});else{x.Score=score;x.Comment=comment?.Trim();x.UpdatedAt=DateTime.UtcNow;}await db.SaveChangesAsync();TempData["Result"]="امتیاز ارزیابی ذخیره شد.";return RedirectToAction(nameof(Evaluations));}

 public record ParametersVm(List<PaymentParameter> Rows);public record LookupVm(List<LookupValue> Rows,List<string> Groups,string Group);
 public record PartsVm(List<Part> Rows,List<LookupValue> Types);public record SuppliersVm(List<Supplier> Rows,List<LookupValue> Activities);
 public record MappingsVm(List<SupplierPart> Rows,List<Supplier> Suppliers,List<Part> Parts);public record EvaluationsVm(List<SupplierPart> Mappings,List<PaymentParameter> Parameters,List<SupplierPartEvaluation> Scores);
}