using System.Security.Cryptography;using System.Text;
using Indamin.Payment.Data;using Microsoft.EntityFrameworkCore;
namespace Indamin.Payment.Services;
public class PaymentCalculationService(AppDbContext db){
 public const decimal WeightTolerance=.0001m;
 public async Task<PaymentWizardState> CalculateAsync(PaymentWizardState s,IReadOnlyList<ImportedPaymentInvoice> imported){
  if(s.TotalAllocationBudget<0)throw new InvalidOperationException("مبلغ قابل تخصیص نمی‌تواند منفی باشد.");var ps=await db.PaymentParameters.Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Title).AsNoTracking().ToListAsync();var totalW=ps.Sum(x=>x.Weight);if(Math.Abs(totalW-100)>WeightTolerance)throw new InvalidOperationException($"جمع وزن پارامترهای فعال باید دقیقاً 100٪ باشد؛ مقدار فعلی {totalW:0.####}٪ است.");
  var parts=await db.Parts.Where(x=>x.IsActive).AsNoTracking().ToListAsync();var sups=await db.Suppliers.Where(x=>x.IsActive).AsNoTracking().ToListAsync();var maps=await db.SupplierParts.Where(x=>x.IsActive&&x.Supplier!.IsActive&&x.Part!.IsActive).AsNoTracking().ToListAsync();var evals=await db.SupplierPartEvaluations.AsNoTracking().ToListAsync();
  var pb=parts.GroupBy(x=>N(x.Title)).Where(g=>g.Count()==1).ToDictionary(g=>g.Key,g=>g.First());var sb=sups.GroupBy(x=>N(x.Title)).Where(g=>g.Count()==1).ToDictionary(g=>g.Key,g=>g.First());var mb=maps.ToDictionary(x=>(x.PartId,x.SupplierId));var em=evals.Where(x=>x.IsActive).GroupBy(x=>(x.SupplierPartId,x.PaymentParameterId)).ToDictionary(g=>g.Key,g=>g.First().Score);var allEm=evals.GroupBy(x=>(x.SupplierPartId,x.PaymentParameterId)).ToDictionary(g=>g.Key,g=>g.First());var prev=await PreviousAsync();var aggregated=Aggregate(imported).ToList();var remainingByKey=aggregated.ToDictionary(x=>KeyHash(x.ReceiptNo,x.Warehouse,x.PartTitle,x.SupplierTitle),x=>Math.Max(0,Math.Round(x.DebtAmount-prev.GetValueOrDefault(KeyHash(x.ReceiptNo,x.Warehouse,x.PartTitle,x.SupplierTitle)),2)));var totalRemainingCurrent=remainingByKey.Values.Sum();var supplierRemaining=aggregated.GroupBy(x=>N(x.SupplierTitle)).ToDictionary(g=>g.Key,g=>g.Sum(x=>remainingByKey[KeyHash(x.ReceiptNo,x.Warehouse,x.PartTitle,x.SupplierTitle)]));var rows=new List<PaymentCalculationRow>();var totalCurrent=imported.Sum(x=>x.DebtAmount);
  foreach(var x in aggregated){if(!pb.TryGetValue(N(x.PartTitle),out var part))throw new InvalidOperationException($"کالا «{x.PartTitle}» در اطلاعات پایه وجود ندارد.");if(!sb.TryGetValue(N(x.SupplierTitle),out var sup))throw new InvalidOperationException($"تامین‌کننده «{x.SupplierTitle}» در اطلاعات پایه وجود ندارد.");if(!mb.TryGetValue((part.Id,sup.Id),out var map))throw new InvalidOperationException($"رابطه فعال قطعه «{part.Title}» و تامین‌کننده «{sup.Title}» تعریف نشده است.");var prior=prev.GetValueOrDefault(KeyHash(x.ReceiptNo,x.Warehouse,part.Title,sup.Title));var remaining=Math.Max(0,Math.Round(x.DebtAmount-prior,2));var age=(s.CalcDate()-x.ReceiptDate.Date).Days;var row=new PaymentCalculationRow{SourceRowNumber=x.RowNumber,ReceiptNo=x.ReceiptNo,Warehouse=x.Warehouse,PartTitle=part.Title,SupplierTitle=sup.Title,PartId=part.Id,SupplierId=sup.Id,OriginalDebt=x.DebtAmount,ReceiptDate=x.ReceiptDate.Date,ReceiptDateJalali=PersianDateService.ToJalali(x.ReceiptDate),ContractSettlementDays=map.ContractSettlementDays,SupplyCapacity=map.SupplyCapacity,SupplierInitialClaimAmount=sup.InitialClaimAmount,DebtAgeDays=age,PreviousAllocated=prior,RemainingDebt=remaining,SupplierOutstandingDebt=supplierRemaining.GetValueOrDefault(N(x.SupplierTitle))};
   foreach(var p in ps){var isInactiveManual=p.ScoringMethod==ParameterScoringMethod.Manual&&allEm.TryGetValue((map.Id,p.Id),out var ev)&&!ev.IsActive;if(isInactiveManual)continue;var raw=p.ScoringMethod==ParameterScoringMethod.DebtAgeEffective?AgeScore(age,map.ContractSettlementDays):p.ScoringMethod==ParameterScoringMethod.DebtAmount?SupplierDebtAmountScore(supplierRemaining.GetValueOrDefault(N(x.SupplierTitle)),totalRemainingCurrent):isInactiveManual?0:em.GetValueOrDefault((map.Id,p.Id),0);if(p.ScoringMethod==ParameterScoringMethod.Manual&&!isInactiveManual&&(raw<1||raw>p.MaxScore))throw new InvalidOperationException($"امتیاز پارامتر «{p.Title}» برای قطعه «{part.Title}» و تامین‌کننده «{sup.Title}» ثبت نشده است.");var score=isInactiveManual?0:Math.Clamp(raw,1,p.MaxScore);row.Scores.Add(new PaymentScoreResult{ParameterId=p.Id,ParameterTitle=p.Title,Type=p.Type,Weight=p.Weight,Score=score,Contribution=isInactiveManual?0:Math.Round(score*p.Weight/100,6),Source=isInactiveManual?"ارزیابی غیرفعال":"ارزیابی قطعه-تامین‌کننده"});}
   row.WeightedScore=row.Scores.Sum(z=>z.Contribution);if(remaining<=0)row.Warning="این بدهی قبلاً به‌طور کامل تخصیص یافته و در این نوبت مبلغی دریافت نمی‌کند.";rows.Add(row);
  }
  s.Parameters=Snap(ps);s.Rows=rows;s.ImportedDebt=totalCurrent;s.RemainingDebt=rows.Sum(x=>x.RemainingDebt);AllocateBudget(s.TotalAllocationBudget,rows);foreach(var row in rows)row.CalculatedAllocatedAmount=row.AllocatedAmount;s.Step=2;return s;
 }
 public static decimal AgeScore(int age,int contract){if(contract<=0)return 5;var a=Math.Max(0,age);if(a<contract*.25m)return 1;if(a<=contract*.50m)return 2;if(a<=contract*.75m)return 1;if(a<=contract)return 4;if(a<=contract+30)return 4;return 5;}
 public static decimal DebtAmountScore(decimal debt,decimal total){if(total<=0)return 1;var p=debt/total*100;if(p<3)return 1;if(p<=10)return 2;if(p<=20)return 3;if(p<=35)return 4;return 5;}
 public static decimal SupplierDebtAmountScore(decimal supplierOutstandingDebt,decimal totalOutstandingDebt)=>DebtAmountScore(supplierOutstandingDebt,totalOutstandingDebt);
 public static void AllocateBudget(decimal budget,List<PaymentCalculationRow> rows){var total=Math.Min(Math.Max(0,budget),rows.Sum(x=>x.RemainingDebt));var rem=total;var active=rows.Where(x=>x.RemainingDebt>0).ToList();foreach(var x in rows){x.AllocatedAmount=0;x.AllocationRatio=0;}for(var guard=0;guard<rows.Count+5&&rem>.005m&&active.Count>0;guard++){var sw=active.Sum(x=>Math.Max(.000001m,x.WeightedScore));foreach(var x in active.ToList()){var share=rem*Math.Max(.000001m,x.WeightedScore)/sw;var room=x.RemainingDebt-x.AllocatedAmount;x.AllocatedAmount=Math.Round(x.AllocatedAmount+Math.Min(share,room),2);}var assigned=rows.Sum(x=>x.AllocatedAmount);rem=Math.Round(total-assigned,2);active=active.Where(x=>x.RemainingDebt-x.AllocatedAmount>.005m).ToList();if(active.Count==0)break;if(active.All(x=>x.RemainingDebt-x.AllocatedAmount>=rem)){}}
  var assigned2=rows.Sum(x=>x.AllocatedAmount);var delta=Math.Round(total-assigned2,2);if(delta!=0&&delta>0){var t=rows.Where(x=>x.RemainingDebt-x.AllocatedAmount>=delta).OrderByDescending(x=>x.WeightedScore).FirstOrDefault();if(t!=null)t.AllocatedAmount=Math.Round(t.AllocatedAmount+delta,2);}else if(delta<0){var t=rows.Where(x=>x.AllocatedAmount>=-delta).OrderByDescending(x=>x.WeightedScore).FirstOrDefault();if(t!=null)t.AllocatedAmount=Math.Round(t.AllocatedAmount+delta,2);}if(total>0)foreach(var x in rows)x.AllocationRatio=Math.Round(x.AllocatedAmount/total,8);
 }
 public static void DistributeSupplierAllocation(decimal target,List<PaymentCalculationRow> rows){target=Math.Round(Math.Max(0,target),2);var max=Math.Round(rows.Sum(x=>Math.Max(0,x.RemainingDebt)),2);if(target>max+.005m)throw new InvalidOperationException($"مبلغ تخصیص تامین‌کننده نمی‌تواند از مانده بدهی او بیشتر باشد. سقف مجاز {max:N0} است.");var calculatedTotal=Math.Round(rows.Sum(x=>Math.Max(0,x.CalculatedAllocatedAmount)),2);if(Math.Abs(target-calculatedTotal)<=.005m){foreach(var row in rows)row.AllocatedAmount=Math.Round(Math.Max(0,Math.Min(row.CalculatedAllocatedAmount,row.RemainingDebt)),2);return;}var weights=rows.ToDictionary(x=>x,x=>x.CalculatedAllocatedAmount>0?x.CalculatedAllocatedAmount:Math.Max(0,x.RemainingDebt));var originalScores=rows.ToDictionary(x=>x,x=>x.WeightedScore);foreach(var row in rows)row.WeightedScore=Math.Max(.000001m,weights[row]);AllocateBudget(target,rows);foreach(var row in rows)row.WeightedScore=originalScores[row];}
 async Task<Dictionary<string,decimal>> PreviousAsync()=>await db.PaymentRunInvoices.Where(x=>!x.PaymentRun!.IsDeleted&&(x.PaymentRun.Status==PaymentRunStatus.Approved||x.PaymentRun.Status==PaymentRunStatus.PaymentOrdered)).GroupBy(x=>x.PaymentKeyHash).Select(g=>new{Key=g.Key,Amount=g.Sum(x=>x.AllocatedAmount)}).ToDictionaryAsync(x=>x.Key,x=>x.Amount);
 static IEnumerable<ImportedPaymentInvoice> Aggregate(IReadOnlyList<ImportedPaymentInvoice> xs)=>xs.GroupBy(x=>new{R=N(x.ReceiptNo),W=N(x.Warehouse),P=N(x.PartTitle),S=N(x.SupplierTitle)}).Select(g=>new ImportedPaymentInvoice(g.Min(x=>x.RowNumber),g.First().ReceiptNo,g.First().Warehouse,g.First().PartTitle,g.First().SupplierTitle,g.Sum(x=>x.DebtAmount),g.Min(x=>x.ReceiptDate)));
 static string N(string s)=>(s??"").Trim().Replace("ي","ی").Replace("ك","ک").ToLowerInvariant();public static string Key(string r,string w,string p,string s)=>string.Join("|",new[]{r,w,p,s}.Select(N)); public static string KeyHash(string r,string w,string p,string s){using var sha=SHA256.Create();return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(Key(r,w,p,s))));}static List<PaymentParameterSnapshot> Snap(List<PaymentParameter> xs)=>xs.Select(x=>new PaymentParameterSnapshot(x.Id,x.Code,x.Title,x.Type,x.Weight,x.MaxScore,x.ScoringGuide,x.ScoringMethod,x.SortOrder)).ToList();
}
public static class PaymentWizardStateExtensions{public static DateTime CalcDate(this PaymentWizardState x)=>PersianDateService.Parse(x.CalculationDateJalali);}
