IF DB_ID(N'IndaminSupplyChainPayment') IS NULL CREATE DATABASE [IndaminSupplyChainPayment];
GO
USE [IndaminSupplyChainPayment];
GO
CREATE TABLE dbo.CompanySettings(Id int NOT NULL CONSTRAINT PK_CompanySettings PRIMARY KEY,CompanyName nvarchar(300) NOT NULL,ShortName nvarchar(100) NOT NULL,SystemName nvarchar(300) NOT NULL,Slogan nvarchar(500) NOT NULL,Website nvarchar(500) NULL,Phone nvarchar(100) NULL,Email nvarchar(200) NULL,Address nvarchar(1000) NULL,EconomicCode nvarchar(100) NULL,NationalId nvarchar(100) NULL,FooterText nvarchar(1000) NULL,PrimaryColor nvarchar(20) NOT NULL,SecondaryColor nvarchar(20) NOT NULL,LogoBytes varbinary(max) NULL,LogoContentType nvarchar(100) NULL,FaviconBytes varbinary(max) NULL,FaviconContentType nvarchar(100) NULL,UpdatedAt datetime2 NOT NULL DEFAULT(sysutcdatetime()));
GO
INSERT dbo.CompanySettings(Id,CompanyName,ShortName,SystemName,Slogan,PrimaryColor,SecondaryColor) VALUES(1,N'ایندامین سایپا',N'ایندامین',N'سامانه تخصیص و پرداخت مالی تامین‌کنندگان',N'با کمک ما برانید',N'#102a43',N'#2d7fb3');
GO
CREATE TABLE dbo.AppUsers(Id int IDENTITY PRIMARY KEY,UserName nvarchar(100) NOT NULL,DisplayName nvarchar(200) NOT NULL,IsAdmin bit NOT NULL DEFAULT(0),IsActive bit NOT NULL DEFAULT(1),PasswordHash nvarchar(1000) NOT NULL);CREATE UNIQUE INDEX UX_AppUsers_UserName ON dbo.AppUsers(UserName);
CREATE TABLE dbo.LookupValues(Id int IDENTITY PRIMARY KEY,GroupCode nvarchar(50) NOT NULL,Code nvarchar(100) NOT NULL,Title nvarchar(200) NOT NULL,SortOrder int NOT NULL DEFAULT(1),IsActive bit NOT NULL DEFAULT(1));CREATE UNIQUE INDEX UX_LookupValues_Group_Code ON dbo.LookupValues(GroupCode,Code);
CREATE TABLE dbo.Parts(Id int IDENTITY PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,TypeId int NOT NULL,IsActive bit NOT NULL DEFAULT(1),CONSTRAINT FK_Parts_Type FOREIGN KEY(TypeId) REFERENCES dbo.LookupValues(Id));CREATE UNIQUE INDEX UX_Parts_Code ON dbo.Parts(Code);
CREATE TABLE dbo.Suppliers(Id int IDENTITY PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,InitialClaimAmount decimal(20,2) NOT NULL DEFAULT(0),IsActive bit NOT NULL DEFAULT(1));CREATE UNIQUE INDEX UX_Suppliers_Code ON dbo.Suppliers(Code);
CREATE TABLE dbo.SupplierActivities(SupplierId int NOT NULL,ActivityId int NOT NULL,CONSTRAINT PK_SupplierActivities PRIMARY KEY(SupplierId,ActivityId),CONSTRAINT FK_SupplierActivities_Supplier FOREIGN KEY(SupplierId) REFERENCES dbo.Suppliers(Id) ON DELETE CASCADE,CONSTRAINT FK_SupplierActivities_Activity FOREIGN KEY(ActivityId) REFERENCES dbo.LookupValues(Id));
CREATE TABLE dbo.SupplierParts(Id int IDENTITY PRIMARY KEY,SupplierId int NOT NULL,PartId int NOT NULL,SupplyCapacity decimal(18,2) NOT NULL,ContractSettlementDays int NOT NULL,IsActive bit NOT NULL DEFAULT(1),CONSTRAINT FK_SupplierParts_Supplier FOREIGN KEY(SupplierId) REFERENCES dbo.Suppliers(Id),CONSTRAINT FK_SupplierParts_Part FOREIGN KEY(PartId) REFERENCES dbo.Parts(Id),CONSTRAINT CK_SupplierParts_Days CHECK(ContractSettlementDays>0),CONSTRAINT CK_SupplierParts_Capacity CHECK(SupplyCapacity>=0));CREATE UNIQUE INDEX UX_SupplierParts_Pair ON dbo.SupplierParts(SupplierId,PartId);
CREATE TABLE dbo.PaymentParameters(Id int IDENTITY PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,Type int NOT NULL,Weight decimal(8,4) NOT NULL,MaxScore decimal(8,2) NOT NULL DEFAULT(5),ScoringGuide nvarchar(max) NOT NULL,ScoringMethod int NOT NULL DEFAULT(0),SortOrder int NOT NULL DEFAULT(1),IsActive bit NOT NULL DEFAULT(1),CONSTRAINT CK_PaymentParameters_Weight CHECK(Weight>=0 AND Weight<=100),CONSTRAINT CK_PaymentParameters_Max CHECK(MaxScore=5));CREATE UNIQUE INDEX UX_PaymentParameters_Code ON dbo.PaymentParameters(Code);
CREATE TABLE dbo.SupplierPartEvaluations(Id int IDENTITY PRIMARY KEY,SupplierPartId int NOT NULL,PaymentParameterId int NOT NULL,Score decimal(8,2) NOT NULL DEFAULT(1),Comment nvarchar(1000) NULL,IsActive bit NOT NULL DEFAULT(1),UpdatedAt datetime2 NOT NULL DEFAULT(sysutcdatetime()),CONSTRAINT FK_SupplierPartEvaluations_Mapping FOREIGN KEY(SupplierPartId) REFERENCES dbo.SupplierParts(Id) ON DELETE CASCADE,CONSTRAINT FK_SupplierPartEvaluations_Parameter FOREIGN KEY(PaymentParameterId) REFERENCES dbo.PaymentParameters(Id),CONSTRAINT CK_SupplierPartEvaluations_Score CHECK(Score>=1 AND Score<=5));CREATE UNIQUE INDEX UX_SupplierPartEvaluations_Pair ON dbo.SupplierPartEvaluations(SupplierPartId,PaymentParameterId);
CREATE TABLE dbo.PaymentRuns(Id int IDENTITY PRIMARY KEY,Title nvarchar(300) NOT NULL,CalculationDateJalali nvarchar(20) NOT NULL,CalculationDate date NOT NULL,PeriodFromJalali nvarchar(20) NOT NULL,PeriodToJalali nvarchar(20) NOT NULL,PeriodFrom date NOT NULL,PeriodTo date NOT NULL,TotalAllocationBudget decimal(20,2) NOT NULL,AmountUnit nvarchar(50) NOT NULL,ImportedDebt decimal(20,2) NOT NULL,RemainingDebt decimal(20,2) NOT NULL,ImportedRowCount int NOT NULL,SourceFileName nvarchar(500) NULL,Notes nvarchar(2000) NULL,Status int NOT NULL,IsDeleted bit NOT NULL DEFAULT(0),DeletedAt datetime2 NULL,DeletedBy int NULL,DeleteReason nvarchar(1000) NULL,PaymentOrderNumber nvarchar(100) NULL,PaymentOrderedAt datetime2 NULL,PaymentOrderedBy int NULL,PreparedByNameSnapshot nvarchar(300) NOT NULL DEFAULT(N''),ConfirmedByNameSnapshot nvarchar(300) NOT NULL DEFAULT(N''),PaymentOrderApproverNameSnapshot nvarchar(300) NOT NULL DEFAULT(N''),CreatedBy int NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT(sysutcdatetime()),ApprovedBy int NULL,ApprovedAt datetime2 NULL,CONSTRAINT FK_PaymentRuns_CreatedBy FOREIGN KEY(CreatedBy) REFERENCES dbo.AppUsers(Id),CONSTRAINT FK_PaymentRuns_ApprovedBy FOREIGN KEY(ApprovedBy) REFERENCES dbo.AppUsers(Id));
CREATE TABLE dbo.PaymentRunParameterSnapshots(Id bigint IDENTITY PRIMARY KEY,PaymentRunId int NOT NULL,PaymentParameterId int NOT NULL,Code nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,Type int NOT NULL,Weight decimal(8,4) NOT NULL,MaxScore decimal(8,2) NOT NULL,ScoringGuide nvarchar(max) NOT NULL,ScoringMethod int NOT NULL,SortOrder int NOT NULL,CONSTRAINT FK_PaymentRunParameterSnapshots_Run FOREIGN KEY(PaymentRunId) REFERENCES dbo.PaymentRuns(Id) ON DELETE CASCADE);CREATE UNIQUE INDEX UX_PaymentRunParameterSnapshots_Key ON dbo.PaymentRunParameterSnapshots(PaymentRunId,PaymentParameterId);
CREATE TABLE dbo.PaymentRunSupplierSummaries(Id int IDENTITY PRIMARY KEY,PaymentRunId int NOT NULL,SupplierId int NOT NULL,SupplierTitle nvarchar(300) NOT NULL,InvoiceCount int NOT NULL,RemainingDebt decimal(20,2) NOT NULL,AllocatedAmount decimal(20,2) NOT NULL,AllocationPercent decimal(12,8) NOT NULL,CONSTRAINT FK_PaymentRunSupplierSummaries_Run FOREIGN KEY(PaymentRunId) REFERENCES dbo.PaymentRuns(Id) ON DELETE CASCADE,CONSTRAINT FK_PaymentRunSupplierSummaries_Supplier FOREIGN KEY(SupplierId) REFERENCES dbo.Suppliers(Id));CREATE UNIQUE INDEX UX_PaymentRunSupplierSummaries_Key ON dbo.PaymentRunSupplierSummaries(PaymentRunId,SupplierId);
CREATE TABLE dbo.PaymentRunInvoices(Id bigint IDENTITY PRIMARY KEY,PaymentRunId int NOT NULL,PaymentKeyHash nvarchar(64) NOT NULL,ReceiptNo nvarchar(150) NOT NULL,Warehouse nvarchar(300) NOT NULL,PartTitle nvarchar(300) NOT NULL,SupplierTitle nvarchar(300) NOT NULL,PartId int NULL,SupplierId int NULL,OriginalDebt decimal(20,2) NOT NULL,ReceiptDate date NOT NULL,ReceiptDateJalali nvarchar(20) NOT NULL,ContractSettlementDays int NOT NULL,SupplyCapacity decimal(18,2) NOT NULL DEFAULT(0),SupplierInitialClaimAmount decimal(20,2) NOT NULL DEFAULT(0),DebtAgeDays int NOT NULL,PreviousAllocated decimal(20,2) NOT NULL,RemainingDebt decimal(20,2) NOT NULL,SupplierOutstandingDebt decimal(20,2) NOT NULL DEFAULT(0),WeightedScore decimal(12,6) NOT NULL,AllocationRatio decimal(12,8) NOT NULL,CalculatedAllocatedAmount decimal(20,2) NOT NULL DEFAULT(0),AllocatedAmount decimal(20,2) NOT NULL,SourceRowNumber int NOT NULL,CONSTRAINT FK_PaymentRunInvoices_Run FOREIGN KEY(PaymentRunId) REFERENCES dbo.PaymentRuns(Id) ON DELETE CASCADE,CONSTRAINT FK_PaymentRunInvoices_Part FOREIGN KEY(PartId) REFERENCES dbo.Parts(Id),CONSTRAINT FK_PaymentRunInvoices_Supplier FOREIGN KEY(SupplierId) REFERENCES dbo.Suppliers(Id));CREATE UNIQUE INDEX UX_PaymentRunInvoices_Key ON dbo.PaymentRunInvoices(PaymentRunId,PaymentKeyHash);
CREATE TABLE dbo.PaymentInvoiceScores(Id bigint IDENTITY PRIMARY KEY,PaymentRunInvoiceId bigint NOT NULL,PaymentParameterId int NOT NULL,Score decimal(8,2) NOT NULL,Weight decimal(8,4) NOT NULL,WeightedContribution decimal(12,6) NOT NULL,ScoringSource nvarchar(100) NOT NULL,ParameterTitleSnapshot nvarchar(300) NOT NULL,ParameterCodeSnapshot nvarchar(100) NOT NULL DEFAULT(N''),ParameterTypeSnapshot int NOT NULL DEFAULT(0),MaxScoreSnapshot decimal(8,2) NOT NULL DEFAULT(5),ScoringGuideSnapshot nvarchar(max) NOT NULL DEFAULT(N''),ScoringMethodSnapshot int NOT NULL DEFAULT(0),CONSTRAINT FK_PaymentInvoiceScores_Invoice FOREIGN KEY(PaymentRunInvoiceId) REFERENCES dbo.PaymentRunInvoices(Id) ON DELETE CASCADE,CONSTRAINT FK_PaymentInvoiceScores_Parameter FOREIGN KEY(PaymentParameterId) REFERENCES dbo.PaymentParameters(Id),CONSTRAINT CK_PaymentInvoiceScores_Score CHECK(Score>=1 AND Score<=5));CREATE UNIQUE INDEX UX_PaymentInvoiceScores_Key ON dbo.PaymentInvoiceScores(PaymentRunInvoiceId,PaymentParameterId);
CREATE TABLE dbo.AuditLogs(Id bigint IDENTITY PRIMARY KEY,Action nvarchar(100) NOT NULL,Entity nvarchar(200) NOT NULL,EntityId nvarchar(100) NOT NULL,Details nvarchar(max) NULL,UserId int NULL,CreatedAt datetime2 NOT NULL DEFAULT(sysutcdatetime()),CONSTRAINT FK_AuditLogs_User FOREIGN KEY(UserId) REFERENCES dbo.AppUsers(Id));
GO
GO
IF OBJECT_ID(N'dbo.AppRoles',N'U') IS NULL CREATE TABLE dbo.AppRoles(Id int IDENTITY PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(200) NOT NULL,IsSystem bit NOT NULL DEFAULT(0),IsActive bit NOT NULL DEFAULT(1));
IF OBJECT_ID(N'dbo.AppPermissions',N'U') IS NULL CREATE TABLE dbo.AppPermissions(Id int IDENTITY PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(200) NOT NULL,GroupTitle nvarchar(200) NOT NULL,SortOrder int NOT NULL DEFAULT(1));
IF OBJECT_ID(N'dbo.AppUserRoles',N'U') IS NULL CREATE TABLE dbo.AppUserRoles(UserId int NOT NULL,RoleId int NOT NULL,CONSTRAINT PK_AppUserRoles PRIMARY KEY(UserId,RoleId),CONSTRAINT FK_AppUserRoles_User FOREIGN KEY(UserId) REFERENCES dbo.AppUsers(Id) ON DELETE CASCADE,CONSTRAINT FK_AppUserRoles_Role FOREIGN KEY(RoleId) REFERENCES dbo.AppRoles(Id) ON DELETE CASCADE);
IF OBJECT_ID(N'dbo.AppRolePermissions',N'U') IS NULL CREATE TABLE dbo.AppRolePermissions(RoleId int NOT NULL,PermissionId int NOT NULL,CONSTRAINT PK_AppRolePermissions PRIMARY KEY(RoleId,PermissionId),CONSTRAINT FK_AppRolePermissions_Role FOREIGN KEY(RoleId) REFERENCES dbo.AppRoles(Id) ON DELETE CASCADE,CONSTRAINT FK_AppRolePermissions_Permission FOREIGN KEY(PermissionId) REFERENCES dbo.AppPermissions(Id) ON DELETE CASCADE);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'UX_AppRoles_Code' AND object_id=OBJECT_ID(N'dbo.AppRoles')) CREATE UNIQUE INDEX UX_AppRoles_Code ON dbo.AppRoles(Code);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'UX_AppPermissions_Code' AND object_id=OBJECT_ID(N'dbo.AppPermissions')) CREATE UNIQUE INDEX UX_AppPermissions_Code ON dbo.AppPermissions(Code);
GO